#!/bin/bash
#################################################
#
# woodworker 0.2
# configurable linux helper script
#
# http://github.com/woodworker/woodworker
# woodworker is licensed under the MIT License
# 
#################################################

WWVERSION="0.2"
WW=`pwd`


function initWoodworker( ){
    mkdir -p $WW/.woodworker/scripts
    mkdir -p $WW/.woodworker/assets
}

if [ ! -d $WW/.woodworker ]
then
    if [[ "$1" == "init" ]]
    then
        echo "Initialisiere woodworker verzeichniss"
        initWoodworker
    else
    	echo "keine woodworker Konfiguration zu finden"
    fi

	exit 0
fi

WWCONF="${WW}/.woodworker"
PROJECT=$1;
ACTION=$2;

if [ "$PROJECT" == "" ]
then
	echo "Kein Projekt übergeben"
	echo "Projektlist: "
	ls $WWCONF/scripts/
	exit 0;
fi



if [ ! -f $WWCONF/scripts/$PROJECT ]
then
	echo "Projektdefinition kann nicht gefunden werden"
	exit 0
fi

ASSETS=$WWCONF/assets/$PROJECT

. $WWCONF/scripts/$PROJECT

if [ "$ACTION" == "" ]
then
	ACTION="index"
fi


FUNC="${PROJECT}_$ACTION"


type "$FUNC" &> /dev/null
FUNCCHECK=$?
if [ ! $FUNCCHECK -eq 0 ]
then
	echo "Methode $ACTION nicht für $PROJECT definiert"
	exit 0
fi

$FUNC
